name: Matrix Demo

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual triggering
  
jobs:
  build: 
    strategy:
      matrix:
        node-version: [12, 14, 16, 18]  # Including node version 18
        operating-system: [ubuntu-latest]
      # Define include and exclude at the matrix level
      include:
        - node-version: 18
          operating-system: ubuntu-latest
      exclude:
        - node-version: 12
          operating-system: windows-latest

    runs-on: ${{ matrix.operating-system }}
    continue-on-error: true # Apply globally for the entire job

    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}  # Correctly reference --node-version
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
